services:
  nginx:
    image: ghcr.io/adeharo9/adeharo-dev:latest
    ports:
      - "8443:443"
    volumes:
      - "ssl-certs:/ssl:ro"
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  ssl-certs:
    external: true
