name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_COMMIT_TAG: ghcr.io/${{github.repository}}:${{github.sha}}
  DOCKER_IMAGE_LATEST_TAG: ghcr.io/${{github.repository}}:latest

jobs:
  test-config-dev:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Docker compose dev configuration'
        run: docker compose -f docker-compose.yml -f deployment/dev/docker-compose.dev.yml config

  test-config-prod:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Docker compose prod configuration'
        run: docker compose -f docker-compose.yml -f deployment/prod/docker-compose.prod.yml config

  publish-docker-image:
    runs-on: ubuntu-latest
    needs:
      - test-config-dev
      - test-config-prod
    permissions:
      packages: write
    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v4

      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags:
            - $DOCKER_IMAGE_COMMIT_TAG
            - $DOCKER_IMAGE_LATEST_TAG

  deploy-to-server:
    runs-on: ubuntu-latest
    needs:
      - publish-docker-image
    steps:
      - name: 'Dummy step'
        run: echo "Success!"
