name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_COMMIT_TAG: ghcr.io/${{github.repository}}:${{github.sha}}
  DOCKER_IMAGE_LATEST_TAG: ghcr.io/${{github.repository}}:latest

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Repository'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Docker Commit Image'
        run: docker build . --tag $DOCKER_IMAGE_COMMIT_TAG

      - name: 'Push Docker Commit Image to GitHub Container Registry'
        run: docker push $DOCKER_IMAGE_COMMIT_TAG

      - name: 'Tag Latest Docker Image'
        run: docker image tag $DOCKER_IMAGE_COMMIT_TAG $DOCKER_IMAGE_LATEST_TAG

      - name: 'Push Latest Docker Image to GitHub Container Registry'
        run: docker push $DOCKER_IMAGE_LATEST_TAG
